const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{planoDeFundo: 0},
	{piso: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{tartaruga: 0},
	{Sólido: 0},
	{Bloco: 0},
	{terra3: 0},
	{piso2: 0},
	{piso3: 0},
	{pise4: 0},
	{Teclado: 0},
	{espinho: 0},
	{lebre: 0},
	{colisao1: 0},
	{txt_cronometro: 0},
	{txt_pontuacao: 0},
	{artefatos: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos: 0},
	{TentarNovamente: 0},
	{txt_sim: 0},
	{txt_nao: 0},
	{Mouse: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{FonteDeSprites: 0},
	{fundoDaLogo: 0},
	{logoSemFundo: 0},
	{btnJogar: 0},
	{fundoLebre: 0},
	{descLebre: 0},
	{descTartaruga: 0},
	{fundoTartaruga: 0},
	{lebreEstatic: 0},
	{tartarugaStatic: 0},
	{ArmazenamentoLocal: 0},
	{txt_highscore: 0},
	{pontuação: 0},
	{highScore: 0},
	{saveID_timeSplit: 0},
	{cronometro: 0}
];

self.InstanceType = {
	planoDeFundo: class extends self.ITiledBackgroundInstance {},
	piso: class extends self.ISpriteInstance {},
	tartaruga: class extends self.ISpriteInstance {},
	Bloco: class extends self.ISpriteInstance {},
	terra3: class extends self.ISpriteInstance {},
	piso2: class extends self.ISpriteInstance {},
	piso3: class extends self.ISpriteInstance {},
	pise4: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	espinho: class extends self.ISpriteInstance {},
	lebre: class extends self.ISpriteInstance {},
	colisao1: class extends self.ISpriteInstance {},
	txt_cronometro: class extends self.ITextInstance {},
	txt_pontuacao: class extends self.ITextInstance {},
	artefatos: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	TentarNovamente: class extends self.ITextInstance {},
	txt_sim: class extends self.ITextInstance {},
	txt_nao: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	fundoDaLogo: class extends self.ISpriteInstance {},
	logoSemFundo: class extends self.ISpriteInstance {},
	btnJogar: class extends self.ISpriteInstance {},
	fundoLebre: class extends self.ISpriteInstance {},
	descLebre: class extends self.ISpriteFontInstance {},
	descTartaruga: class extends self.ISpriteFontInstance {},
	fundoTartaruga: class extends self.ISpriteInstance {},
	lebreEstatic: class extends self.ISpriteInstance {},
	tartarugaStatic: class extends self.ISpriteInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	txt_highscore: class extends self.ITextInstance {}
}